Add Resource loading API (resolves #106)
Minestom/Minestom pull request #122
Opened 2021-01-27 18:08 UTC by mworzala

This adds a simple api to read files from the extension jar resources, as well as preference over files in the extension directory.

The obvious use case here is config files.

2021-04-22 09:42 UTC, kezz requested changes
Looks great to me! Just a few minor comments

2021-04-22 09:42 UTC, kezz commented on src/main/java/net/minestom/server/extensions/Extension.java
> +    public InputStream getResource(@NotNull String fileName) {
I wonder if this should be a path instead - they can be relative to the jar/data directory. I just hare dealing with separators :')

2021-04-22 09:42 UTC, kezz commented on src/main/java/net/minestom/server/extensions/Extension.java
> +            final URL url = getClass().getClassLoader().getResource(fileName);
Should this not use the extension class loader? Can be pulled from the origin.

2021-04-22 09:42 UTC, kezz commented on src/main/java/net/minestom/server/extensions/ExtensionManager.java
> +            Field dataDirectoryField = Extension.class.getDeclaredField("dataDirectory");
This could live in the origin - would enable others to easily get the data folder for an extension and also reduce the amount of reflection we do.

2021-05-21 02:29 UTC, mworzala commented
Closing due to issue with origin repository. Recreated as #302

2021-05-21 02:29 UTC, closed without merging