added a public Direction facing() method in Pos.java
Minestom/Minestom pull request #1226
Opened 2022-07-11 11:12 UTC by bananasmoothii

Hello, this is my first pull request here ! This can be useful for WorldEdit-like stuff

2022-07-12 04:15 UTC, KrystilizeNevaDies commented
Specific ranges for yaw and pitch are unnecessary, you should be able to have 1000 yaw, as a solution, you can mod the yaw/pitch where needed.

2022-07-12 07:03 UTC, bananasmoothii commented
But clients don't even support more than 90 / less than -90 pitch ? As for the yaw, I saw it is automatically "fixed" to be between -180 and 180

2022-07-12 11:09 UTC, KrystilizeNevaDies commented
Making already existing code break because of that is an issue though, we can mod the yaw if the client complains, but I think it's not a great idea to enforce that on the Dev.

2022-07-14 12:49 UTC, Kebab11noel commented
Well I think the range annotation can stay since the pitch range is standard, anything outside -90 and 90 doesn't make sense, but the client accepts values outside it so the runtime check should be gone. I have the same opinion for the yaw, it shouldn't be force fixed but at this point removing it would be a hidden breaking change.

2022-07-14 13:09 UTC, bananasmoothii commented
Yes, I didn't touch to the yaw, I think it is good like this, for example for things like incrementing the yaw a little at each tick to make a player rotate, it would be annoying having to manually fix the yaw. As for the pitch, I don't see any use for it being less than -90 or more than 90... But I can remove that check throwing an exception if needed

2022-07-21 20:17 UTC, bananasmoothii commented on src/main/java/net/minestom/server/coordinate/Pos.java
> +        if (pitch < -90 || pitch > 90) throw new IllegalArgumentException("Pitch must be between -90 and 90");
Yes I will do it, along with the range annotation in the record header

2022-08-06 09:20 UTC, bananasmoothii commented
ok, I removed the range annotation as long as ```java
if (pitch < -90 || pitch > 90) throw new IllegalArgumentException("Pitch must be between -90 and 90");
```

2022-08-06 09:30 UTC, mworzala requested changes
With annotation gone and tests I am happy

2022-08-06 09:30 UTC, mworzala commented on src/main/java/net/minestom/server/coordinate/Pos.java
> +    @Range(from = -180, to = 180)
Remove

2025-07-11 16:14 UTC, mworzala approved these changes

2025-07-11 16:15 UTC, merged