Add commit info from JitPack into Minestom's jar
Minestom/Minestom pull request #1272
Opened 2022-07-22 19:22 UTC by off-by-0point5

Adds a `Git` class holding information about the build from JitPack.
So any extension or server implementation would have access to these.

I took group and artifact fields too, so one can tell what fork of Minestom is used.

2022-10-17 17:28 UTC, Geolykt commented
Are you sure that it is viable to have the fields set as `static final`? Javac tends to inline those fields so any extensions will only know which version they compiled against at best, but not which version is currently running

2022-10-27 10:00 UTC, off-by-0point5 commented
> Javac tends to inline those fields so any extensions will only know which version they compiled against at best, but not which version is currently running

Didn't know that.
Do you know if it is better to make the fields just `public static` or make them `private static final` and use getters?

2022-10-27 11:11 UTC, Geolykt commented
I believe that is up to you. I'd personally say `private static final` as these fields wouldn't be able to be modified - so JIT will have an easier time on that front

2022-10-27 11:48 UTC, off-by-0point5 commented
I did that. But I'm still not sure if this will be merged eventually...

2022-10-27 11:57 UTC, Geolykt commented
The getters should be static too

2022-10-27 12:13 UTC, TheMode requested changes

2022-10-27 12:13 UTC, TheMode commented on src/main/java/net/minestom/server/Git.java
> +public class Git {
Class should be `final`

2022-10-27 12:13 UTC, TheMode commented on src/main/java/net/minestom/server/Git.java
> +    public String getCommit() { return COMMIT; }
Drop the `get` prefix in all the getter. So just `commit` in this case

2022-12-31 02:55 UTC, mworzala approved these changes

2022-12-31 03:09 UTC, merged