Add convenience playSound method in Instance class
Minestom/Minestom pull request #1305
Opened 2022-08-01 23:45 UTC by GreatWyrm

This PR adds a convenience method to the Instance class so it is quicker to play sounds in that instance.

2022-08-01 23:53 UTC, mworzala approved these changes

2022-08-02 01:05 UTC, mworzala requested changes
My approval was a lie it turns out, @TheMode made a good point that this should be in the adventure audience along with the other playSound methods [here](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/adventure/audience/PacketGroupingAudience.java#L100).

2022-08-02 02:02 UTC, GreatWyrm commented
Alright, moved the method to the PacketGroupingAudience class.

2022-08-02 10:23 UTC, mworzala approved these changes

2022-08-02 10:23 UTC, merged