Add a way to override hasPermission method
Minestom/Minestom pull request #1474
Opened 2022-10-24 12:40 UTC by LoisDuplain

Permission manager plugins needs to override hasPermission method.

Can be used like any other events:

```java
	public void handlePlayerCheckPermissionEvent(PlayerCheckPermissionEvent event) {
		boolean hasPermission = event.hasPermission();

		if (hasPermission)
			return;
		
		final Player player = event.getPlayer();

		// Your behavior

		event.setHasPermission(/* true or false */);
	}
```

2022-11-04 13:12 UTC, dev-hydrogen requested changes

2022-11-04 13:12 UTC, dev-hydrogen commented on src/main/java/net/minestom/server/event/player/PlayerCheckPermissionEvent.java
> +    public PlayerCheckPermissionEvent(Player player, Permission permission, String permissionName, boolean hasPermission) {
Why use a Player here? Just use the PermissionHandler itself instead. Not everything that has permissions is a player entity.

2022-11-04 13:12 UTC, dev-hydrogen commented on src/main/java/net/minestom/server/permission/PermissionHandler.java
> +        if (this instanceof Player player) {
Again using Player leaves out ConsoleSenders aswell as ServerSenders, possibly more

2022-11-04 13:12 UTC, dev-hydrogen commented on src/main/java/net/minestom/server/permission/PermissionHandler.java
> +        if (this instanceof Player player) {
I dont think the *exact same event* should override both the hasPermission method without a verifier and the one with a verifier. Possibly split it up to 2 events, or a nullable PermissionVerifier in the original event?
Again, just return the PermissionHandler here too.

2022-11-04 13:12 UTC, dev-hydrogen commented on src/main/java/net/minestom/server/event/player/PlayerCheckPermissionEvent.java
> +public class PlayerCheckPermissionEvent implements PlayerEvent {
This should not be a PlayerEvent.

2022-11-04 13:12 UTC, dev-hydrogen commented on src/main/java/net/minestom/server/event/player/PlayerCheckPermissionEvent.java
> +    private final String permissionName;
Why do you need both the permission as well as its name? You can just get the name from the Permission object easily.

2022-11-12 15:51 UTC, HSGamer commented
I did something similar but for `PermissionHandler`
#1138 
Man, it's old now.

2022-12-26 17:56 UTC, dev-hydrogen commented
@LoisDuplain you should probably address the issues i commented on if you still want this merged

2024-12-03 15:47 UTC, mworzala commented
Permissions are removed as of #2445

2024-12-03 15:47 UTC, closed without merging