minestom-ce pull-back
Minestom/Minestom pull request #1937
Opened 2023-09-04 17:45 UTC by mworzala

This PR brings back most of the changes from [minestom-ce](https://github.com/hollow-cube/minestom-ce), though some cases the changes are modified.

> [!NOTE]
> There are a lot of minestom-ce references still, I will remove them. The extension change was pulled in by accident, see below for plan.

### Not pulled (or modified):
* **Extension removal** will not be brought back at this time. There will however be an option to opt-in or opt-out (not sure which) of extensions.
* **Logger removal** has not yet been pulled in here, though it probably will before merge. Terminal removal will probably become an opt-in or opt-out feature rather than removed completely.

### Changes (at a high level):
* 1.19.4 (need to merge in some changes from https://github.com/Minestom/Minestom/pull/1873)
* 1.20.1
* Gradle rework
  * Simplification
  * Maven central publishing (needs some work still, see below)
* BlockPlacementRule update
  * Support most vanilla use cases
  * Remove existing rules (will probably either publish the set I have separately or add them here)
* [And more...](https://github.com/hollow-cube/minestom-ce/blob/main/CHANGELOG.md#changelog)

### Maven Central
How to handle maven releases is a bit up in the air, in my mind there are two competing options described below. Please provide feedback/opinions in this thread or in discord if you have any.

#### Split snapshots/releases

Snapshots (either located at `net.minestom:minestom-snapshots:{version}`, or at `net.minestom:minestom:{version}` in the sonatype staging repository) will be both commit tagged (eg `d11cee55d2`) and PR-branch tagged (eg `my_pr_branch-d11cee55d2`).

Releases (located at `net.minestom:minestom:{version}`) will be tagged to specific game versions, with either a date based versioning scheme (eg `2023.9.4+1.20.1`) or a semantic version (eg `1.2.3+1.20.1`). These versions would presumedly be significantly less frequent and include more changes. This will likely come with a later PR.

#### Single release

Releases (at `net.minestom:minestom:{version}`) will be added when the repository is tagged manually with a new version only. They would follow a semantic version tied to a game version, eg `1.2.3+1.20.1`. Potentially PR branches would be published to another repo as well.

2023-09-04 19:36 UTC, Nuckerr commented
Imo, do split snapshots/releases. Without that, versions would be fractured over multiple repositories, better to keep it on the same repo.

2023-09-04 20:44 UTC, mworzala commented
What do you mean they would be fractured over repositories?

2023-09-05 08:40 UTC, Nuckerr commented
You would have to go to jitpack for snapshots, and central for releases (unless I've misunderstood)

2023-09-06 14:59 UTC, mworzala commented
In any case jitpack is going away

2023-09-13 04:07 UTC, GreatWyrm requested changes
Alright went through a bunch of the files and left my comments.

Overall, I like the changes, although I have a few small concerns over it.

2023-09-13 04:07 UTC, GreatWyrm commented on src/main/java/net/minestom/server/world/biomes/Biome.java
> +                element.setByte("has_precipitation", (byte) 1); //todo bad fix
Could address this quickly with another member variable in this class, unless you have other things in mind to do.

2023-09-18 21:16 UTC, mworzala commented on build.gradle.kts
> +                password.set(System.getenv("SONATYPE_PASSWORD"))
yes

2023-09-18 21:16 UTC, mworzala commented on demo/src/main/java/net/minestom/demo/Main.java
> +        blockManager.registerHandler(TestBlockHandler.INSTANCE.getNamespaceId(), () -> TestBlockHandler.INSTANCE);
meh its the demo, half of it is test code

2023-09-18 21:19 UTC, mworzala commented on src/main/java/net/minestom/server/ServerFlag.java
> +    public static final boolean TERMINAL_SUPPORT_HEX_COLOR = PropertyUtils.getBoolean("minestom.terminal.support-hex-color", true);
Boolean.getBoolean does not support a default

2023-09-18 21:20 UTC, mworzala commented on src/main/java/net/minestom/server/command/builder/arguments/Argument.java
> +        this.defaultValue = unused -> defaultValue.get();
this.defaultValue is a function not a supplier

2023-09-18 21:24 UTC, mworzala commented
For now I will set it to publish commits to `minestom-snapshots`, it can be changed in the future.

2024-02-08 13:11 UTC, MelonHell commented
What's up with this pull request now?

2024-02-08 18:49 UTC, mworzala commented
Still planned, just haven't gotten to updating it yet.

2024-02-09 19:13 UTC, DasBabyPixel commented
Terminal and extension removal getting merged?

2024-02-09 19:27 UTC, merged

2024-02-09 19:30 UTC, DasBabyPixel commented
Publishing gonna get fixed so we can get Minestom on central?

2024-02-09 19:31 UTC, mworzala commented
Yes.