Serialize ItemStacks in system chat
Minestom/Minestom pull request #2501
Opened 2024-12-01 03:25 UTC by GreatWyrm

2024-12-23 13:12 UTC, mworzala commented on src/main/java/net/minestom/server/network/ComponentNetworkBufferTypeImpl.java
> +            BinaryTagWriter nbtWriter = impl(buffer).nbtWriter;
this is duplicated from NbtTypeImpl, this logic should just be moved into NetworkBufferTypeImpl, eg `impl(buffer).nbtWriter()`, same for reader.

2024-12-23 13:17 UTC, mworzala commented on src/main/java/net/minestom/server/component/DataComponentMapImpl.java
> +    public void forEach(@NotNull BiConsumer<DataComponent<?>, Object> consumer) {
These are not good and need to be resolved before this is merged.

Some options (none of which I am not in love with currently):
* Change the consumer to return ints and let the caller handle it
* track the ID->DataComponent mapping internally

I think tracking the id mapping is the most obvious option, but I am not that excited about increasing the memory footprint of ItemStack :(

2024-12-27 20:39 UTC, mworzala commented on src/main/java/net/minestom/server/network/ComponentNetworkBufferTypeImpl.java
> +                    if (minestomDataComponentValue.value().equals(DataComponentValue.removed())) {
this is wrong, it should be a check on `entry.getValue()`, not the value of our MinestomDataComponentValue which only holds added components.

2025-01-19 21:44 UTC, TheMeinerLP requested changes

2025-01-19 21:44 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/adventure/provider/NBTLegacyHoverEventSerializer.java
> +@Deprecated
Can you add some reason why is deprecated as a javadoc comment ?

2025-01-19 21:44 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/component/DataComponentMapImpl.java
> +        // TODO: This only works for itemComponent, fix
Can you remove or open a issue for the todo ?

2025-01-19 21:44 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +import java.io.*;
Please prevent * imports

2025-01-19 21:44 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +        return nbtReader;
Looks dirty

2025-01-19 21:44 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +        }
Looks dirty

2025-01-19 21:44 UTC, TheMeinerLP commented on src/test/java/net/minestom/server/adventure/TestCanCreateHoverEvent.java
> +public class TestCanCreateHoverEvent {
remove public

2025-01-19 21:44 UTC, TheMeinerLP commented on src/test/java/net/minestom/server/adventure/TestCanCreateHoverEvent.java
> +    public void createHoverEvent() {
Also here remove public

2025-01-20 02:48 UTC, GreatWyrm commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +import java.io.*;
Feels unnecessary (IntelliJ auto-groups imports into * if you have too many), but changed

2025-01-20 02:50 UTC, GreatWyrm commented on src/main/java/net/minestom/server/component/DataComponentMapImpl.java
> +        // TODO: This only works for itemComponent, fix
See https://github.com/Minestom/Minestom/pull/2501#discussion_r1895745862, this won't be merged without some solution being figured out.

2025-01-20 02:50 UTC, GreatWyrm commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +        return nbtReader;
Non-actionable feedback, it's the best way to my knowledge of doing this.

2025-01-20 02:50 UTC, GreatWyrm commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +        }
Non-actionable feedback

2025-01-20 05:09 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/network/NetworkBufferImpl.java
> +        }
So I could imagine that you make a package private input and outstream or subclass

2025-01-20 05:10 UTC, TheMeinerLP commented on src/main/java/net/minestom/server/component/DataComponentMapImpl.java
> +        // TODO: This only works for itemComponent, fix
Then we should consider it a “draft” until then

2025-03-25 15:00 UTC, closed without merging

2025-03-25 15:00 UTC, mworzala commented
Superseded/expanded on by https://github.com/Minestom/Minestom/commit/514656a504b3e5bdecdb06c77f5c7b90b5b6b6f0 on 1.21.5