Create FencePlacementRule.java
Minestom/Minestom pull request #306
Opened 2021-05-25 02:04 UTC by andrew-bilotti

Works better than wallplacementrule for fences!

2021-05-25 12:36 UTC, mworzala requested changes

2021-05-25 12:36 UTC, mworzala commented on src/main/java/net/minestom/server/instance/block/rule/vanilla/FencePlacementRule.java
> +    Block block;
This should be private (and final).

2021-05-25 12:36 UTC, mworzala commented on src/main/java/net/minestom/server/instance/block/rule/vanilla/FencePlacementRule.java
> +    private boolean isBlock(Instance instance, int x, int y, int z) {
a more descriptive method name would be good here. Something like `isFenceBlock`

2023-03-29 22:04 UTC, KrystilizeNevaDies commented
Closed due to inactivity. Feel free to open again.

2023-03-29 22:04 UTC, closed without merging