Add ArgumentSoundEvent to ArgumentType
Minestom/Minestom pull request #345
Opened 2021-06-29 02:31 UTC by LeoDog896

This adds a sound event argument to the ArgumentType list, to allow for selecting custom/normal sounds client side.

2021-06-29 09:55 UTC, kezz commented
If this argument accepts custom sounds, returning a `SoundEvent` is wrong as that only supports built-in sounds. Probably worth either changing this to return `Sound.Type`, which can either be a `SoundEvent` or just a custom sound with a key. This would allow people to `instanceof` to check if they have a `SoundEvent` or not.

2021-06-29 13:18 UTC, kezz requested changes

2021-06-29 13:18 UTC, kezz commented on src/main/java/net/minestom/server/command/builder/arguments/minecraft/registry/ArgumentSound.java
> + * Represents an argument giving an {@link EntityType}.
```suggestion
 * Represents an argument giving an {@link Sound.Type}.
 ```

2021-06-29 17:51 UTC, TheMode commented
> If this argument accepts custom sounds, returning a `SoundEvent` is wrong as that only supports built-in sounds. Probably worth either changing this to return `Sound.Type`, which can either be a `SoundEvent` or just a custom sound with a key. This would allow people to `instanceof` to check if they have a `SoundEvent` or not.

Should be fine once we are done replacing the enums

2021-07-01 08:14 UTC, kezz approved these changes

2024-05-03 17:47 UTC, closed without merging