Additional ways to interact with extensions
Minestom/Minestom pull request #465
Opened 2021-09-15 16:11 UTC by new-maxim724

As I wrote in the discord, this will help to decouple the implementation and only give access to the abstraction. It also saves us from casting the type to the required one.

Why am I not using Class<? extends Extension> ? Since we cannot inherit the interface from Extension, we have to do this.
On the one hand, this is not entirely secure, but on the other hand, we know that the ExtensionManager only loads Extension subclasses.

As example:
![image](https://user-images.githubusercontent.com/89523915/133469713-d61c7c12-5c8e-4de9-bff6-e5891e03c1e4.png)

2021-09-15 17:13 UTC, jglrxavpok requested changes
Probably won't work as-is due to different extensions having separate extensions.
Have you checked in "real" setting with separate jars for two extensions and a third jar with a Minestom implementation?

Extension A will have a different value when loading 'TestExtension.class' than the value Extension B will have.

2021-09-15 17:13 UTC, jglrxavpok commented on src/main/java/net/minestom/server/extensions/ExtensionManager.java
> +                .filter(extension -> extension.getClass().isAssignableFrom(type))
This won't work if different extensions try to access the same types: 
Extension A will have a different value when loading 'TestExtension.class' than the value Extension B will have.

2021-09-15 17:13 UTC, jglrxavpok commented on src/main/java/net/minestom/server/extensions/ExtensionManager.java
> +                .anyMatch(extension -> extension.getClass().isAssignableFrom(type));
Same goes.

2021-12-09 13:54 UTC, mworzala commented
I'm not really sure the goal here, but if it is still relevant after #537 please re open as an issue or PR to that branch. In the mean time, closing due to inactivity and in favor of #537

2021-12-09 13:54 UTC, closed without merging