Make argb values with no alpha return MapColors#NONE
Minestom/Minestom pull request #693
Opened 2022-02-18 14:27 UTC by LooFifteen

This PR allows `MapColors#closestColor` to return colour `NONE` when no alpha value is provided.

[Related Discussion](https://github.com/Minestom/Minestom/discussions/692)

2022-02-18 14:42 UTC, jglrxavpok requested changes
While I agree with the intent of this PR, you risk breaking all current code using this API.
I do think alpha support is interesting, but we should not change too much from the current format (RGB -> RGBA requires a shift in addition to specifying the alpha bits, while RGB->ARGB only requires the addition of alpha bits)

2022-02-18 14:42 UTC, jglrxavpok commented on src/main/java/net/minestom/server/map/MapColors.java
> +        if (argb << 24 == 0) return new PreciseMapColor(NONE, Multiplier.x1_00);
That's not ARGB but RGBA.

2022-02-18 14:42 UTC, jglrxavpok commented on src/test/java/map/TestMapColors.java
> +        assertEquals(MapColors.closestColor(0xFFFFFF00).getBaseColor(), MapColors.NONE);
Ditto

2022-02-18 15:14 UTC, SLLCoding commented on src/main/java/net/minestom/server/map/MapColors.java
> +        if (argb << 24 == 0) return new PreciseMapColor(NONE, Multiplier.x1_00);
Oh, whoops

2023-03-30 21:53 UTC, KrystilizeNevaDies commented
Closed due to no longer being relevant. Feel free to reopen.

2023-03-30 21:53 UTC, closed without merging